name: the violet burning
favicon: null
layout_spectrum: 1
typography_spectrum: 0.58037
title: the violet burning
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#030303'
    - '#535353'
    - '#2b2b2b'
    - '#8f8f8f'
  brandStrength: 0.9092207427602261
  lightness: 0
  saturation: 0.6684462241828442
  rhythmicContrast: 0.09359883167780936
purpose: []
